### ISSUE TITLE
Release Testing: 1-1(메인화면-로그인check)

### ISSUE THREAD

**Issue by kweonyaeji** [usageness/SE_TEAM_04#12]
오류를 재연하기 위해 필요한 조치 (즉, 어떻게 하여 오류를 발견하였나)
- 로그인 입력 창에서 로그인 또는 비밀번호를 잘못 입력하고 로그인을 실행하였을 때, 페이지가 무한 로딩되기만 하는 오류를 발견하였습니다.

예상했던 동작이나 결과
- 로그인 입력 창에 잘못 입력하였을 경우 아이디 또는 비밀번호를 잘못 입력하였다 라는 것을 알리고 다시 입력할 수 있도록 유도하는 것을 예상하였습니다.

실제 나타난 동작이나 결과
- 로그인 입력 창에 잘못 입력하고 로그인을 실행하면 해당 메인 페이지가 무한 로딩됩니다.

가능한 경우 오류 수정을 위한 제안.
- 로그인을 체크하는 과정을 따로 만들고 그곳에서 아이디 / 비밀번호 일치 여부를 확인합니다.
그리고 아이디와 비밀번호가 db에서의 정보와 일치하지 않게 입력된 경우 '아이디 또는 비밀번호를 잘못 입력하였습니다.'를 alert로 띄우고, history.back()을 합니다.

**Comment by usageness** [comment]
이슈 확인하였습니다.

아이디/패스워드가 모두 일치하지 않는 경우 경고창에 해당 경고 문구가 출력되고 있으나,

입력한 아이디를 DB에서 찾은 경우 유효하지 않은 패스워드 입력시 예외 처리 로직이 구현되지 않은점을 확인했습니다.

해당 로직을 추가하여 픽스 완료하였고, 파이널 테스팅 배포 버젼에 적용될 예정입니다.
