### ISSUE TITLE
Release Testing: 1-7(공통-Header)

### ISSUE THREAD

**Issue by seoh0215** [usageness/SE_TEAM_04#13]
각 페이지에 공유되는 header 레이아웃에 온라인 쇼핑몰 로고 및 쇼핑몰의 이름이 들어가 있지 않습니다. 장바구니나 이벤트 페이지를 들어가면 header에 로고나 쇼핑몰 이름이 뜨지 않습니다. 메인 화면의 상단에 있는 로고를 header로 옮기거나 footer에 있는 메인 홈으로 가는 링크를 header로 옮기는 것을 권장합니다.

**Comment by usageness** [comment]
메인화면 상단의 검색창을 포함하고 있는 영역을 header로 이동시켰습니다.

파이널 테스팅 배포 판에 적용될 예정입니다.
