### ISSUE TITLE
Release Testing: 2-3(메인화면-최신등록상품의 상세정보화면)

### ISSUE THREAD

**Issue by kweonyaeji** [usageness/SE_TEAM_04#15]
오류를 재연하기 위해 필요한 조치 (즉, 어떻게 하여 오류를 발견하였나)
- 최신등록상품을 클릭하였을 때 상세정보페이지의 헤더와 푸터만 표시되는 오류를 발견하였습니다.

예상했던 동작이나 결과
- 최신등록상품을 클릭하면 해당 상품에 대한 상세정보 및 기능이 표시되는 것을 예상하였습니다.

실제 나타난 동작이나 결과
- 최신등록상품을 클릭하면 해당 상품에 대한 상세정보 및 기능이 나타나지 않고 헤더와 푸터만 표시됩니다.

**Comment by usageness** [comment]
최신 등록 상품을 클릭하면 상세정보 페이지로 이동되도록 수정하였습니다.

파이널 테스팅 배포때 적용될 예정입니다.
