### ISSUE TITLE
Release Testing: 2-9(상품목록 - 표시)

### ISSUE THREAD

**Issue by ehrwk** [usageness/SE_TEAM_04#16]
특정상품을 클릭했을 때 상품의 상세화면으로 이동이 되지 않습니다.

상세정보 페이지를 구현하거나 링크해주시길 바랍니다.

**Comment by usageness** [comment]
상세정보 페이지로 링크되도록 수정되었습니다.

파이널 테스팅 배포때 적용될 예정입니다.
