### ISSUE TITLE
Release Testing: 2-14~2-17,2-19~2-21(상품 상세정보)

### ISSUE THREAD

**Issue by JunginO** [usageness/SE_TEAM_04#17]
메인페이지 상에서 상세페이지 접속하기 위해 최신등록상품 클릭 시 상세정보페이지 내용이 미출력 되었습니다.
페이지를 구성하는 헤더와 푸터 만 출력되는 상황입니다.

메인페이지에서 Search를 눌렀을 때 보여지는 상품 목록들 리스트에서 상품 목록을 눌렀을 때 페이지 이동이 일어나지 않았습니다. 상세정보페이지 링크가 연결되지 않은것 같습니다.

http://ec2-3-37-87-181.ap-northeast-2.compute.amazonaws.com:3000/product/21

**Comment by usageness** [comment]
상세 정보 페이지의 내용이 출력되도록 수정되었습니다.

또한 검색 내역에서 보이는 목록을 클릭했을시 상세 정보 페이지로 이동하도록 수정하였습니다.

파이널 테스팅 배포에 적용될 예정입니다.
